services:
  db:
    image: pgvector/pgvector:0.8.1-pg16-trixie
    container_name: vector_rdb
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis
    ports:
      - "8888:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

