"""Add timestamps to User and Item

Revision ID: 13f1f61c37b3
Revises: c84efe9d21e3
Create Date: 2025-12-20 15:40:04.053728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '13f1f61c37b3'
down_revision = 'c84efe9d21e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False))
    op.add_column('item', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('item', 'updated_at')
    op.drop_column('item', 'created_at')
    # ### end Alembic commands ###
