"""update MealLog

Revision ID: 4a76c983592d
Revises: d5a9edfd2d36
Create Date: 2025-12-24 14:13:44.996311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4a76c983592d'
down_revision = 'd5a9edfd2d36'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Enum 타입을 정의합니다. (models.py에 적힌 한글 값들과 일치해야 함)
    # name='mealtype'은 DB에 저장될 타입 이름입니다.
    meal_type_enum = sa.Enum('아침', '점심', '저녁', '간식', name='mealtype')

    # 2. [중요] DB에 Enum 타입을 먼저 생성합니다.
    meal_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meallog', sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=True))
    op.add_column('meallog', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meallog', 'updated_at')
    op.drop_column('meallog', 'meal_type')
    # ### end Alembic commands ###
    # 2. [중요] 사용이 끝난 Enum 타입을 DB에서 삭제합니다.
    meal_type_enum = sa.Enum('아침', '점심', '저녁', '간식', name='mealtype')
    meal_type_enum.drop(op.get_bind())
