"""Fix utcnow -> now

Revision ID: 6062cb874a3d
Revises: 13f1f61c37b3
Create Date: 2025-12-20 15:45:24.552658

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6062cb874a3d'
down_revision = '13f1f61c37b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
