"""먹은 음식 추가할때 날짜 선택필드 추가 

Revision ID: bf45a2f8d82b
Revises: 5cfca3ee1ff9
Create Date: 2025-12-24 15:01:40.362275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf45a2f8d82b'
down_revision = '5cfca3ee1ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
