services:
  neo4j:
    image: neo4j:latest
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/config:/config
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/MyPassWord@
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always